# Generated by Django 3.1.7 on 2021-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
